name: outdoor_dashboard
description: Outdoor activities dashboard.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mapbox_gl: ^0.16.0
  gpx: ^2.2.1
  http: ^1.1.0
  ansicolor: ^2.0.1
  path: ^1.8.3
  google_polyline_algorithm: ^3.1.0
  provider: ^6.0.5
  intl: ^0.18.1
  pointer_interceptor: ^0.9.3+6
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/outdoor_data/

flutter_intl:
  enabled: true
